# you can read more about security in the related section of the documentation
# http://symfony.com/doc/current/book/security.html

security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        in_memory:
            memory:
                users:
                    user:  { password: userpass, roles: [ 'ROLE_USER' ] }
                    admin: { password: escpeurope1819, roles: [ 'ROLE_ADMIN' ] }

    firewalls:
            # ...
            main:
                pattern:   ^/
                anonymous: true

                provider:  in_memory
                form_login:
                    login_path: login
                    check_path: login_check
                logout:
                    path:   logout
                    target: /platform

    access_control:
        - { path: ^/fr/paris/admin/*  , roles: ROLE_ADMIN }
        - { path: ^/en/paris/admin/*  , roles: ROLE_ADMIN }
        - { path: ^/fr/paris/edit/*  , roles: ROLE_ADMIN }
        - { path: ^/en/paris/edit/*  , roles: ROLE_ADMIN }